# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1da56d4bb25e1977dbe3027d89f3238b83db5e1fb959cfde31cdda9c37090026be251214d29ac4f004a5393276a631731c973159f38c03edd8381291fc2bbbc

test:
  secret_key_base: 7cd214e47eaa29fe589db6015160ac172969d36a2fe440e769941933bee842ce04e5a7d37bab94e530a6d0d24f66c9ae15d84282c1e63bebd69b83d69004e210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
